### ISSUE TITLE
非常有意思的项目！不过我有点好奇使用场景？🤔🤔

### ISSUE THREAD

**Issue by willemswang** [caoyingjunz/kubez-autoscaler#7]
想请教一下：
为什么要把 HPA 的配置放在 Annotation 里面？
如果为了同一配置管理，一个 YAML 里面本身可以放多个 YAML，这样感觉更清晰一点。

恕我能力有限，目前看到的好处是：不同自己再设置引用对象，减少了这个操作。

但是这样的实现方式带来了一个问题：用户如果自己在 HPA 里修改，是不是会被 Annotation 直接再覆盖回去？还是说下次 Annotation 更新时，才会更新 HPA 里的配置？但是后面这种方式会导致有段时间 Annotation 里的配置和 HPA 里的配置不同，可能会给用户困惑。

**Comment by caoyingjunz** [comment]
1.  本项目用于实时维护源生的 workload 和 hpa 之间的状态，hpa的 创建或删除完全由 workload 来决定，统一入口，简化操作。用户只需在注释中新增两三天配置即可，剩下的交给  kubez-autoscaler  控制器即可。

2. 由 kubez-autoscaler 维护的hpa，用户无法修改或者删除，只能通过 deployment/ sts 的注释来维护

**Comment by willemswang** [comment]
> 1. 本项目用于实时维护源生的 workload 和 hpa 之间的状态，hpa的 创建或删除完全由 workload 来决定，统一入口，简化操作。用户只需在注释中新增两三条配置即可，剩下的交给  kubez-autoscaler  控制器即可。
> 2. 由 kubez-autoscaler 维护的hpa，用户无法修改或者删除，只能通过 deployment/ sts 的注释来维护

感谢大佬的解答
